### ISSUE TITLE
CT: iframe api failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/beers-law-lab#232]
```
beers-law-lab : phet-io-tests : assert
6 out of 7 tests passed. 1 failed.
SimTests: beers-law-lab: iframe api failed:
phetioDocumentation expected for beersLawLab.concentrationScreen.view.soluteControls.soluteComboBox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543913814604:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: beers-law-lab: iframe api failed:
phetioDocumentation expected for beersLawLab.beersLawScreen.view.solutionControls.comboBox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543913814604:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)


id: Bayes Chrome
Approximately 12/3/2018, 11:09:04 PM
beers-law-lab : phet-io-tests : assert
6 out of 7 tests passed. 1 failed.
SimTests: beers-law-lab: iframe api failed:
phetioDocumentation expected for beersLawLab.concentrationScreen.view.soluteControls.soluteComboBox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543930172303:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: beers-law-lab: iframe api failed:
phetioDocumentation expected for beersLawLab.beersLawScreen.view.solutionControls.comboBox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543930172303:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)


id: Bayes Chrome
Approximately 12/3/2018, 11:09:04 PM
beers-law-lab : phet-io-tests : no-assert
6 out of 7 tests passed. 1 failed.
SimTests: beers-law-lab: iframe api failed:
phetioDocumentation expected for beersLawLab.concentrationScreen.view.soluteControls.soluteComboBox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543910575918:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: beers-law-lab: iframe api failed:
phetioDocumentation expected for beersLawLab.beersLawScreen.view.solutionControls.comboBox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543910575918:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)


id: Bayes Chrome
Approximately 12/3/2018, 11:09:04 PM
beers-law-lab : phet-io-tests : no-assert
6 out of 7 tests passed. 1 failed.
SimTests: beers-law-lab: iframe api failed:
phetioDocumentation expected for beersLawLab.concentrationScreen.view.soluteControls.soluteComboBox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543924312729:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: beers-law-lab: iframe api failed:
phetioDocumentation expected for beersLawLab.beersLawScreen.view.solutionControls.comboBox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543924312729:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)


id: Bayes Chrome
Approximately 12/3/2018, 11:09:04 PM
beers-law-lab : phet-io-tests : no-assert
6 out of 7 tests passed. 1 failed.
SimTests: beers-law-lab: iframe api failed:
phetioDocumentation expected for beersLawLab.concentrationScreen.view.soluteControls.soluteComboBox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543930986454:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)

SimTests: beers-law-lab: iframe api failed:
phetioDocumentation expected for beersLawLab.beersLawScreen.view.solutionControls.comboBox
    at https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/js/tests/SimTests.js?bust=1543930986454:269:20
    at dispatch (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:304:56)
    at windowMessageListener (https://bayes.colorado.edu/continuous-testing/snapshot-1543903744057/phet-io-wrappers/common/js/Client.js:364:13)


id: Bayes Chrome
Approximately 12/3/2018, 11:09:04 PM
```

**Comment by pixelzoom** [comment]
This is caused by https://github.com/phetsims/phet-io/issues/1418, nothing sim specific to do.
