### ISSUE TITLE
CT: Tandem was required but not supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/beers-law-lab#235]
```
beers-law-lab : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/assert/js/assert.js:22:13)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/tandem/js/Tandem.js?bust=1554201307325:97:21)
    at ToggleNode.register (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/tandem/js/PhetioObject.js?bust=1554201307325:294:19)
    at ToggleNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/tandem/js/PhetioObject.js?bust=1554201307325:281:12)
    at ToggleNode.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/scenery/js/nodes/Node.js?bust=1554201307325:4974:12)
    at ToggleNode.Node [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/scenery/js/nodes/Node.js?bust=1554201307325:526:12)
    at new ToggleNode (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/sun/js/ToggleNode.js?bust=1554201307325:60:10)
    at new SolutionControls (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/beers-law-lab/js/beerslaw/view/SolutionControls.js?bust=1554201307325:55:22)
    at new BeersLawScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/beers-law-lab/js/beerslaw/view/BeersLawScreenView.js?bust=1554201307325:46:28)
    at BeersLawScreen.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/beers-law-lab/js/beerslaw/BeersLawScreen.js?bust=1554201307325:44:34)
id: Bayes Chrome
Approximately 4/2/2019, 1:23:35 AM
beers-law-lab : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/assert/js/assert.js:22:13)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/tandem/js/Tandem.js?bust=1554205350096:97:21)
    at ToggleNode.register (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/tandem/js/PhetioObject.js?bust=1554205350096:294:19)
    at ToggleNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/tandem/js/PhetioObject.js?bust=1554205350096:281:12)
    at ToggleNode.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/scenery/js/nodes/Node.js?bust=1554205350096:4974:12)
    at ToggleNode.Node [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/scenery/js/nodes/Node.js?bust=1554205350096:526:12)
    at new ToggleNode (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/sun/js/ToggleNode.js?bust=1554205350096:60:10)
    at new SolutionControls (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/beers-law-lab/js/beerslaw/view/SolutionControls.js?bust=1554205350096:55:22)
    at new BeersLawScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/beers-law-lab/js/beerslaw/view/BeersLawScreenView.js?bust=1554205350096:46:28)
    at BeersLawScreen.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/beers-law-lab/js/beerslaw/BeersLawScreen.js?bust=1554205350096:44:34)
id: Bayes Chrome
Approximately 4/2/2019, 1:23:35 AM
beers-law-lab : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/assert/js/assert.js:22:13)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/tandem/js/Tandem.js?bust=1554201307325:97:21)
    at ToggleNode.register (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/tandem/js/PhetioObject.js?bust=1554201307325:294:19)
    at ToggleNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/tandem/js/PhetioObject.js?bust=1554201307325:281:12)
    at ToggleNode.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/scenery/js/nodes/Node.js?bust=1554201307325:4974:12)
    at ToggleNode.Node [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/scenery/js/nodes/Node.js?bust=1554201307325:526:12)
    at new ToggleNode (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/sun/js/ToggleNode.js?bust=1554201307325:60:10)
    at new SolutionControls (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/beers-law-lab/js/beerslaw/view/SolutionControls.js?bust=1554201307325:55:22)
    at new BeersLawScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/beers-law-lab/js/beerslaw/view/BeersLawScreenView.js?bust=1554201307325:46:28)
    at BeersLawScreen.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/beers-law-lab/js/beerslaw/BeersLawScreen.js?bust=1554201307325:44:34)
id: Bayes Chrome
Approximately 4/2/2019, 1:23:35 AM
beers-law-lab : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: Tandem was required but not supplied
Error: Assertion failed: Tandem was required but not supplied
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/assert/js/assert.js:22:13)
    at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/tandem/js/Tandem.js?bust=1554205350096:97:21)
    at ToggleNode.register (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/tandem/js/PhetioObject.js?bust=1554205350096:294:19)
    at ToggleNode.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/tandem/js/PhetioObject.js?bust=1554205350096:281:12)
    at ToggleNode.mutate (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/scenery/js/nodes/Node.js?bust=1554205350096:4974:12)
    at ToggleNode.Node [as constructor] (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/scenery/js/nodes/Node.js?bust=1554205350096:526:12)
    at new ToggleNode (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/sun/js/ToggleNode.js?bust=1554205350096:60:10)
    at new SolutionControls (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/beers-law-lab/js/beerslaw/view/SolutionControls.js?bust=1554205350096:55:22)
    at new BeersLawScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/beers-law-lab/js/beerslaw/view/BeersLawScreenView.js?bust=1554205350096:46:28)
    at BeersLawScreen.createView (https://bayes.colorado.edu/continuous-testing/snapshot-1554189815256/beers-law-lab/js/beerslaw/BeersLawScreen.js?bust=1554205350096:44:34)
id: Bayes Chrome
Approximately 4/2/2019, 1:23:35 AM
beers-law-lab : phet-io-tests : assert
7 out of 7 tests passed. 0 failed.

Approximately 4/2/2019, 1:23:35 AM
beers-law-lab : phet-io-tests : no-assert
7 out of 7 tests passed. 0 failed.

Approximately 4/2/2019, 1:23:35 AM
```

Wondering if this is another CT error.  Sorry if it is.

**Comment by KatieWoe** [comment]
Actually, I'm seeing this error in a lot of places.  May make a general issue somewhere.

**Comment by KatieWoe** [comment]
General issue made: https://github.com/phetsims/tandem/issues/83.  Closing
