### ISSUE TITLE
CT required tandems must be supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/beers-law-lab#258]
```
beers-law-lab : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/beers-law-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22beers-law-lab%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599640382837%22%2C%22timestamp%22%3A1599641102990%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:240:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:189:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/axon/js/Action.js:92:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/scenery/js/listeners/PressListener.js:245:23)
at new CuvetteNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/view/CuvetteNode.js:97:27)
at new BeersLawScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/view/BeersLawScreenView.js:38:25)
at BeersLawScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/BeersLawScreen.js:38:16)
at BeersLawScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/joist/js/Screen.js:296:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/joist/js/Sim.js:835:16)
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM

----------------------------------

beers-law-lab : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/beers-law-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22beers-law-lab%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599640382837%22%2C%22timestamp%22%3A1599653084263%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:240:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:189:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/axon/js/Action.js:92:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/scenery/js/listeners/PressListener.js:245:23)
at new CuvetteNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/view/CuvetteNode.js:97:27)
at new BeersLawScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/view/BeersLawScreenView.js:38:25)
at BeersLawScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/BeersLawScreen.js:38:16)
at BeersLawScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/joist/js/Screen.js:296:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/joist/js/Sim.js:835:16)
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM

----------------------------------

beers-law-lab : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/phet-io-wrappers/mirror-inputs/?sim=beers-law-lab&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22beers-law-lab%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599640382837%22%2C%22timestamp%22%3A1599641775058%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:240:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:189:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/axon/js/Action.js:92:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/scenery/js/listeners/PressListener.js:245:23)
at new CuvetteNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/view/CuvetteNode.js:97:27)
at new BeersLawScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/view/BeersLawScreenView.js:38:25)
at BeersLawScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/BeersLawScreen.js:38:16)
at BeersLawScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/joist/js/Screen.js:296:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/joist/js/Sim.js:835:16)
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM

----------------------------------

beers-law-lab : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/phet-io-wrappers/mirror-inputs/?sim=beers-law-lab&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22beers-law-lab%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599640382837%22%2C%22timestamp%22%3A1599653202073%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:240:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:189:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/axon/js/Action.js:92:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/scenery/js/listeners/PressListener.js:245:23)
at new CuvetteNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/view/CuvetteNode.js:97:27)
at new BeersLawScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/view/BeersLawScreenView.js:38:25)
at BeersLawScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/BeersLawScreen.js:38:16)
at BeersLawScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/joist/js/Screen.js:296:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/joist/js/Sim.js:835:16)
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM

----------------------------------

beers-law-lab : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/phet-io-wrappers/state/?sim=beers-law-lab&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22beers-law-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599640382837%22%2C%22timestamp%22%3A1599641953618%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:240:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:189:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/axon/js/Action.js:92:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/scenery/js/listeners/PressListener.js:245:23)
at new CuvetteNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/view/CuvetteNode.js:97:27)
at new BeersLawScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/view/BeersLawScreenView.js:38:25)
at BeersLawScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/BeersLawScreen.js:38:16)
at BeersLawScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/joist/js/Screen.js:296:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/joist/js/Sim.js:835:16)
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM

----------------------------------

beers-law-lab : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/phet-io-wrappers/state/?sim=beers-law-lab&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22beers-law-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599640382837%22%2C%22timestamp%22%3A1599646913551%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:240:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:189:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/axon/js/Action.js:92:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/scenery/js/listeners/PressListener.js:245:23)
at new CuvetteNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/view/CuvetteNode.js:97:27)
at new BeersLawScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/view/BeersLawScreenView.js:38:25)
at BeersLawScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/BeersLawScreen.js:38:16)
at BeersLawScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/joist/js/Screen.js:296:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/joist/js/Sim.js:835:16)
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM

----------------------------------

beers-law-lab : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/studio/?sim=beers-law-lab&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22beers-law-lab%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599640382837%22%2C%22timestamp%22%3A1599641453202%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:240:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:189:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/axon/js/Action.js:92:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/scenery/js/listeners/PressListener.js:245:23)
at new CuvetteNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/view/CuvetteNode.js:97:27)
at new BeersLawScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/view/BeersLawScreenView.js:38:25)
at BeersLawScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/BeersLawScreen.js:38:16)
at BeersLawScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/joist/js/Screen.js:296:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/joist/js/Sim.js:835:16)
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM

----------------------------------

beers-law-lab : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/studio/?sim=beers-law-lab&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22beers-law-lab%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1599640382837%22%2C%22timestamp%22%3A1599655312003%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:240:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:189:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/axon/js/Action.js:92:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/scenery/js/listeners/PressListener.js:245:23)
at new CuvetteNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/view/CuvetteNode.js:97:27)
at new BeersLawScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/view/BeersLawScreenView.js:38:25)
at BeersLawScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/BeersLawScreen.js:38:16)
at BeersLawScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/joist/js/Screen.js:296:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/joist/js/Sim.js:835:16)
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM

----------------------------------

beers-law-lab : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/phet-io-wrappers/phet-io-wrappers-tests.html?sim=beers-law-lab&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: beers-law-lab: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:240:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:189:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/axon/js/Action.js:92:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/scenery/js/listeners/PressListener.js:245:23)
at new CuvetteNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/view/CuvetteNode.js:97:27)
at new BeersLawScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/view/BeersLawScreenView.js:38:25)
at BeersLawScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/BeersLawScreen.js:38:16)
at BeersLawScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/joist/js/Screen.js:296:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/joist/js/Sim.js:835:16)

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM

----------------------------------

beers-law-lab : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/phet-io-wrappers/phet-io-wrappers-tests.html?sim=beers-law-lab
3 out of 4 tests passed. 1 failed.
SimTests: beers-law-lab: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/assert/js/assert.js:22:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:240:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/tandem/js/PhetioObject.js:189:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/axon/js/Action.js:92:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/scenery/js/listeners/PressListener.js:245:23)
at new CuvetteNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/view/CuvetteNode.js:97:27)
at new BeersLawScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/view/BeersLawScreenView.js:38:25)
at BeersLawScreen.createView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/beers-law-lab/js/beerslaw/BeersLawScreen.js:38:16)
at BeersLawScreen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/joist/js/Screen.js:296:23)
at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1599640382837/joist/js/Sim.js:835:16)

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 9/9/2020, 2:33:02 AM
```

**Comment by pixelzoom** [comment]
This regression occurred when converting to PressListener for #257.    Fixed above, closing.
