### ISSUE TITLE
CT Assertion failed: unexpected number of particles removed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/beers-law-lab#284]
```
beers-law-lab : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/phet-io-wrappers/state/?sim=beers-law-lab&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22beers-law-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648314385011%22%2C%22timestamp%22%3A1648351537023%7D
Uncaught Error: Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/assert/js/assert.js:25:13)
at Precipitate.removeParticles (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/beers-law-lab/js/concentration/model/Precipitate.js:96:15)
at Precipitate.updateParticles (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/beers-law-lab/js/concentration/model/Precipitate.js:64:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/beers-law-lab/js/concentration/model/Precipitate.js:39:60
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/Property.js:227:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/Property.js:156:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/Property.js:227:23)
id: Bayes Chrome
Snapshot from 3/26/2022, 11:06:25 AM

----------------------------------

beers-law-lab : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/phet-io-wrappers/state/?sim=beers-law-lab&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22beers-law-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648314385011%22%2C%22timestamp%22%3A1648450110720%7D
Uncaught Error: Uncaught Error: Assertion failed
Error: Assertion failed
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/assert/js/assert.js:25:13)
at Precipitate.removeParticles (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/beers-law-lab/js/concentration/model/Precipitate.js:96:15)
at Precipitate.updateParticles (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/beers-law-lab/js/concentration/model/Precipitate.js:64:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/beers-law-lab/js/concentration/model/Precipitate.js:39:60
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/Property.js:227:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/Property.js:156:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648314385011/chipper/dist/js/axon/js/Property.js:227:23)
id: Bayes Chrome
Snapshot from 3/26/2022, 11:06:25 AM
```

**Comment by pixelzoom** [comment]
Manually mapping the stack trace from .js to .ts .... This assertion failed at line 108 in Precipitate.ts:

```js
    const removedParticles = particles.slice( particles.length - numberToRemove, numberToRemove );
    assert && assert( removedParticles && removedParticles.length === numberToRemove );
```

**Comment by pixelzoom** [comment]
In the above commit, I added an assertion message, to provide a bit more info.   But beers-law-lab has not been touched in a very long time, I've never seen this error before, and I can't reproduce it with local fuzzing.  So I'm guessing it's either a very rare corner case, or something related specifically to the State wrapper.

**Comment by pixelzoom** [comment]
This is not specific to the State wrapper. It's just difficult for CT to reproduce. I was able to reproduce this manually, running unbuilt with this URL:
`beers-law-lab/beers-law-lab_en.html?brand=phet&ea&debugger`

Steps:
1. Go to _Concentration_ screen
2. Choose "Potassium permanganate" from the Solute combo box, because it precipitates quickly.
3. Shake the shaker until "Saturated!" appears in the beaker, and there is visible precipitate.
4. Using the drain faucet, start draining solution from the beaker.  Or using the water facuet, add water to the beaker. Both actions cause precipitate to disappear, and the assertion failure will occur.

Every failure that I was able to produce had this message, expecting 1 and removing 0:

> unexpected number of particles removed: expected 1, removed 0

**Comment by pixelzoom** [comment]
From duplicate https://github.com/phetsims/beers-law-lab/issues/286, here's a more recent stack trace with the improved assertion message:

```
beers-law-lab : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/phet-io-wrappers/state/?sim=beers-law-lab&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22beers-law-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649735346764%7D
Uncaught Error: Uncaught Error: Assertion failed: unexpected number of particles removed: expected 3, removed 0
Error: Assertion failed: unexpected number of particles removed: expected 3, removed 0
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/assert/js/assert.js:25:13)
at Precipitate.removeParticles (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/beers-law-lab/js/concentration/model/Precipitate.js:96:15)
at Precipitate.updateParticles (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/beers-law-lab/js/concentration/model/Precipitate.js:64:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/beers-law-lab/js/concentration/model/Precipitate.js:39:60
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/Property.js:218:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/Property.js:147:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/Property.js:218:23)
id: Bayes Chrome
Snapshot from 4/11/2022, 7:50:57 PM
```

**Comment by pixelzoom** [comment]
In the above commit, I replaced a bad `splice` -- I don't know how this was working at all.

Closing.
