### ISSUE TITLE
CT: required tandems must be supplied

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#285]
Caused by #278.

```
beers-law-lab : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/beers-law-lab/beers-law-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22beers-law-lab%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1648932021285%22%2C%22timestamp%22%3A1648936938669%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/assert/js/assert.js:25:13)
at PhetioAction.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/tandem/js/PhetioObject.js:134:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/tandem/js/PhetioObject.js:107:12)
at new PhetioDataHandler (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/tandem/js/PhetioDataHandler.js:65:5)
at new PhetioAction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/tandem/js/PhetioAction.js:56:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/scenery/js/listeners/PressListener.js:170:25)
at new DragListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/scenery/js/listeners/DragListener.js:136:5)
at new SliderTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/sun/js/SliderTrack.js:71:25)
at new SpectrumSliderTrack (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/scenery-phet/js/SpectrumSliderTrack.js:37:5)
at new WavelengthNumberControl (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1648932021285/chipper/dist/js/scenery-phet/js/WavelengthNumberControl.js:71:20)
id: Bayes Chrome
Snapshot from 4/2/2022, 2:40:21 PM
```

**Comment by pixelzoom** [comment]
Fixed over in https://github.com/phetsims/scenery-phet/issues/730.
