### ISSUE TITLE
CT MigrationReport problem: phetioIDNotInNewAPI

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/beers-law-lab#335]
```
beers-law-lab : migration : 1.7->main : assert
http://128.138.93.172/continuous-testing/ct-snapshots/1700494000325/phet-io-wrappers/migration/?sim=beers-law-lab&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&oldVersion=1.7&migrationRate=5000&phetioMigrationReport=assert&wrapperContinuousTest=%7B%22test%22%3A%5B%22beers-law-lab%22%2C%22migration%22%2C%221.7-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1700494000325%22%2C%22timestamp%22%3A1700494505154%7D
Assertion failed: MigrationReport problem: phetioIDNotInNewAPI

{
"clientMessages": [],
"stateSchemaIncompatible": [],
"initialStatesAreIncompatible": [],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [
"beersLawLab.beersLawScreen.model.detector.absorbanceProperty.dependencies.beersLawLab-beersLawScreen-model-solutionInCuvette-absorbanceProperty",
"beersLawLab.beersLawScreen.model.detector.transmittanceProperty.dependencies.beersLawLab-beersLawScreen-model-detector-pathLengthProperty",
"beersLawLab.beersLawScreen.model.detector.transmittanceProperty.dependencies.beersLawLab-beersLawScreen-model-solutionInCuvette-transmittanceProperty"
],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": [],
"expectedReportErrorNotFound": []
}
[object Object]
Error: Assertion failed: MigrationReport problem: phetioIDNotInNewAPI
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1700494000325/assert/js/assert.js:28:13)
at assert (MigrationReport.ts:193:22)
at reportForContext (MigrationReport.ts:313:11)
at reportAPIChanges (MigrationEngine.ts:89:22)
at migrate (StandardPhetioWrapper.ts:279:37)
at (Client.ts:1523:19)
at async (http://128.138.93.172/continuous-testing/ct-snapshots/1700494000325/phet-io-wrappers/migration/migration.js:217:13)
[URL] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1700494000325%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Dbeers-law-lab%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26oldVersion%3D1.7%26migrationRate%3D5000%26phetioMigrationReport%3Dassert&duration=80000&testInfo=%7B%22test%22%3A%5B%22beers-law-lab%22%2C%22migration%22%2C%221.7-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1700494000325%22%2C%22timestamp%22%3A1700494505154%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/wrapper-test.html?url=..%2F..%2Fct-snapshots%2F1700494000325%2Fphet-io-wrappers%2Fmigration%2F%3Fsim%3Dbeers-law-lab%26locales%3D*%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue%26fuzz%26oldVersion%3D1.7%26migrationRate%3D5000%26phetioMigrationReport%3Dassert&duration=80000&testInfo=%7B%22test%22%3A%5B%22beers-law-lab%22%2C%22migration%22%2C%221.7-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1700494000325%22%2C%22timestamp%22%3A1700494505154%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1700494000325/phet-io-wrappers/migration/?sim=beers-law-lab&locales=*&phetioDebug=true&phetioWrapperDebug=true&fuzz&oldVersion=1.7&migrationRate=5000&phetioMigrationReport=assert&wrapperContinuousTest=%7B%22test%22%3A%5B%22beers-law-lab%22%2C%22migration%22%2C%221.7-%3Emain%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1700494000325%22%2C%22timestamp%22%3A1700494505154%7D
[NAVIGATED] about:blank
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1700494000325/studio/?sim=beers-law-lab&exposeStandardPhetioWrapper&phetioWrapperDebug=true&fuzz&wrapperContinuousTest={%22test%22:[%22beers-law-lab%22,%22migration%22,%221.7-%3Emain%22,%22assert%22],%22snapshotName%22:%22snapshot-1700494000325%22,%22timestamp%22:1700494505154}&phetioMigrationReport=assert&locales=*
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1700494000325/beers-law-lab/beers-law-lab_en.html?brand=phet-io&ea&debugger&postMessageOnError&sim=beers-law-lab&exposeStandardPhetioWrapper&phetioWrapperDebug=true&fuzz&wrapperContinuousTest={%22test%22:[%22beers-law-lab%22,%22migration%22,%221.7-%3Emain%22,%22assert%22],%22snapshotName%22:%22snapshot-1700494000325%22,%22timestamp%22:1700494505154}&phetioMigrationReport=assert&locales=*&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[NAVIGATED] https://phet-io.colorado.edu/sims/beers-law-lab/1.7/wrappers/studio/?exposeStandardPhetioWrapper&phetioWrapperDebug=true&fuzz&wrapperContinuousTest={%22test%22:[%22beers-law-lab%22,%22migration%22,%221.7-%3Emain%22,%22assert%22],%22snapshotName%22:%22snapshot-1700494000325%22,%22timestamp%22:1700494505154}&phetioMigrationReport=assert
[NAVIGATED] about:blank
[CONSOLE] enabling assert
[NAVIGATED] https://phet-io.colorado.edu/sims/beers-law-lab/1.7/beers-law-lab_all_phet-io_debug.html?ea&postMessageOnError&exposeStandardPhetioWrapper&phetioWrapperDebug=true&fuzz&wrapperContinuousTest={%22test%22:[%22beers-law-lab%22,%22migration%22,%221.7-%3Emain%22,%22assert%22],%22snapshotName%22:%22snapshot-1700494000325%22,%22timestamp%22:1700494505154}&phetioMigrationReport=assert&phetioEmitAPIBaseline&phetioCreateArchetypes&phetioEmitHighFrequencyEvents=false
[CONSOLE] enabling assert
[CONSOLE] continuous-test-wrapper-load
[CONSOLE] Assertion failed: MigrationReport problem: phetioIDNotInNewAPI

{
"clientMessages": [],
"stateSchemaIncompatible": [],
"initialStatesAreIncompatible": [],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [
"beersLawLab.beersLawScreen.model.detector.absorbanceProperty.dependencies.beersLawLab-beersLawScreen-model-solutionInCuvette-absorbanceProperty",
"beersLawLab.beersLawScreen.model.detector.transmittanceProperty.dependencies.beersLawLab-beersLawScreen-model-detector-pathLengthProperty",
"beersLawLab.beersLawScreen.model.detector.transmittanceProperty.dependencies.beersLawLab-beersLawScreen-model-solutionInCuvette-transmittanceProperty"
],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": [],
"expectedReportErrorNotFound": []
} JSHandle@object
[PAGE ERROR] Error: Error: Assertion failed: MigrationReport problem: phetioIDNotInNewAPI

{
"clientMessages": [],
"stateSchemaIncompatible": [],
"initialStatesAreIncompatible": [],
"propertyValidValueNoLongerSupported": [],
"switchedFromInvalidValueToNewDefault": [],
"phetioIDNotInNewAPI": [
"beersLawLab.beersLawScreen.model.detector.absorbanceProperty.dependencies.beersLawLab-beersLawScreen-model-solutionInCuvette-absorbanceProperty",
"beersLawLab.beersLawScreen.model.detector.transmittanceProperty.dependencies.beersLawLab-beersLawScreen-model-detector-pathLengthProperty",
"beersLawLab.beersLawScreen.model.detector.transmittanceProperty.dependencies.beersLawLab-beersLawScreen-model-solutionInCuvette-transmittanceProperty"
],
"notStatefulAnymore": [],
"incompletePhetioElementRenames": [],
"incompletePhetioElementDeletes": [],
"processedNothing": [],
"newNeededIOTypes": {},
"relatedIOTypesForValueRenameHaveUnexpectedSchemas": [],
"missingStringPhetioElements": [],
"expectedReportErrorNotFound": []
}
[object Object]
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1700494000325/assert/js/assert.js:28:13)
at MigrationReport.reportForContext (http://128.138.93.172/continuous-testing/ct-snapshots/1700494000325/chipper/dist/js/phet-io-wrappers/common/js/migration/MigrationReport.js:161:23)
at MigrationReport.reportAPIChanges (http://128.138.93.172/continuous-testing/ct-snapshots/1700494000325/chipper/dist/js/phet-io-wrappers/common/js/migration/MigrationReport.js:252:12)
at MigrationEngine.migrate (http://128.138.93.172/continuous-testing/ct-snapshots/1700494000325/chipper/dist/js/phet-io-wrappers/common/js/migration/MigrationEngine.js:67:23)
at StandardPhetioWrapper.loadStandardPhetioWrapperFromHTML (http://128.138.93.172/continuous-testing/ct-snapshots/1700494000325/chipper/dist/js/phet-io-wrappers/common/js/StandardPhetioWrapper.js:196:38)
at async Client.loadStandardPhetioWrapperFromHTML (http://128.138.93.172/continuous-testing/ct-snapshots/1700494000325/chipper/dist/js/phet-io-wrappers/common/js/Client.js:1346:20)
at async http://128.138.93.172/continuous-testing/ct-snapshots/1700494000325/phet-io-wrappers/migration/migration.js:217:13
[CONSOLE] continuous-test-wrapper-error

id: "Sparky Node Puppeteer"
Snapshot from 11/20/2023, 8:26:40 AM
```

**Comment by pixelzoom** [comment]
@KatieWoe This looks like a duplicate of https://github.com/phetsims/beers-law-lab/issues/334.  Or am I missing something?

**Comment by KatieWoe** [comment]
Looks like. Sorry, I was scanning the labels of the issues. Closing
